// @generated by protoc-gen-es v0.1.1 with parameter "target=ts"
// @generated from file carrel/common/task_state/v1/task_state_v1.proto (package carrel.common.task_state.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * / A common tag for carrel system.
 *
 * @generated from enum carrel.common.task_state.v1.TaskState
 */
export enum TaskState {
  /**
   * @generated from enum value: TASK_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * something planed but not on immediate agenda
   *
   * @generated from enum value: TASK_STATE_PLANNED = 1;
   */
  PLANNED = 1,

  /**
   * immediate agenda
   *
   * @generated from enum value: TASK_STATE_TODO = 2;
   */
  TODO = 2,

  /**
   * currently doing
   *
   * @generated from enum value: TASK_STATE_WORKING = 3;
   */
  WORKING = 3,

  /**
   * done
   *
   * @generated from enum value: TASK_STATE_FINISHED = 4;
   */
  FINISHED = 4,

  /**
   * failed
   *
   * @generated from enum value: TASK_STATE_FAILED = 5;
   */
  FAILED = 5,

  /**
   * cancelled
   *
   * @generated from enum value: TASK_STATE_CANCELLED = 6;
   */
  CANCELLED = 6,

  /**
   * to revisite
   *
   * @generated from enum value: TASK_STATE_TO_REVISIT = 7;
   */
  TO_REVISIT = 7,
}
// Retrieve enum metadata with: proto3.getEnumType(TaskState)
proto3.util.setEnumType(TaskState, "carrel.common.task_state.v1.TaskState", [
  { no: 0, name: "TASK_STATE_UNSPECIFIED" },
  { no: 1, name: "TASK_STATE_PLANNED" },
  { no: 2, name: "TASK_STATE_TODO" },
  { no: 3, name: "TASK_STATE_WORKING" },
  { no: 4, name: "TASK_STATE_FINISHED" },
  { no: 5, name: "TASK_STATE_FAILED" },
  { no: 6, name: "TASK_STATE_CANCELLED" },
  { no: 7, name: "TASK_STATE_TO_REVISIT" },
]);

