[package]
name = "carrel_core"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
default = ["test_helper"]
test_helper = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
# Carrel systems
carrel_scaffold = { path = "../carrel_scaffold" }
carrel_db = {path = "../carrel_db"}
carrel_utils = { path = "../carrel_utils", features = ["faker"] }
carrel_app_db = { path = "../carrel_app_db" }

# The reason fireflies is not in `carrel_fireflies` is because fireflies is still useful as independent app (for managing totags in files), while carrel_scaffold is not without using carrel.
firefly_keeper = { path = "../../firefly_keeper" }
serde = { version = "1.0.145", features = ["derive"] }
serde_yaml = { version = "0.9.13" }
serde_json = "1.0.85"
prost = "0.11.0"
carrel_commons = { path = "../../carrel_commons" }
pdf_gongju = { path = "../../pdf_gongju" }
figment = { version = "0.10", features = ["yaml", "env"] }


uuid = { version = "1.1.2", features = ["serde", "v4"] }
thiserror = "1.0"
async-trait = "0.1.57"
sea-orm={version = "0.9.2", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "mock",
    "macros",
    "debug-print",
    "uuid"
]}
once_cell = "1.15.0"

pebble_query = { path = "../../pebble_query" }

to_core = { path = "../../to/to_core" }

[build-dependencies]
carrel_utils = { path = "../carrel_utils"}
