[package]
name = "carrel_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["", "entity","migration"]


[dependencies]
migration = { path = "migration" }
carrel_commons = { path = "../../carrel_commons" }
entity = { path = "entity" }
tokio = { version = "^1", features = ["full"] }
carrel_utils = { path = "../carrel_utils" }
pebble_query = { path = "../../pebble_query" }
once_cell = "1.15.0"
thiserror = "1.0.26"
serde_json = "1.0.85"
chrono = { version = "0.4.19", features = ["serde"] }
sea-orm={version = "0.9.3", features = [
    "sqlx-sqlite",
   "runtime-tokio-rustls",
    "mock",
    "macros",
    "debug-print",
    "uuid"
]}
