// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: test_prof.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CarrelTestServiceClient is the client API for CarrelTestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CarrelTestServiceClient interface {
	Test(ctx context.Context, in *CarrelTestRequest, opts ...grpc.CallOption) (*CarrelTestResponse, error)
}

type carrelTestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCarrelTestServiceClient(cc grpc.ClientConnInterface) CarrelTestServiceClient {
	return &carrelTestServiceClient{cc}
}

func (c *carrelTestServiceClient) Test(ctx context.Context, in *CarrelTestRequest, opts ...grpc.CallOption) (*CarrelTestResponse, error) {
	out := new(CarrelTestResponse)
	err := c.cc.Invoke(ctx, "/carrel.test_proto.CarrelTestService/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarrelTestServiceServer is the server API for CarrelTestService service.
// All implementations must embed UnimplementedCarrelTestServiceServer
// for forward compatibility
type CarrelTestServiceServer interface {
	Test(context.Context, *CarrelTestRequest) (*CarrelTestResponse, error)
	mustEmbedUnimplementedCarrelTestServiceServer()
}

// UnimplementedCarrelTestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCarrelTestServiceServer struct {
}

func (UnimplementedCarrelTestServiceServer) Test(context.Context, *CarrelTestRequest) (*CarrelTestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedCarrelTestServiceServer) mustEmbedUnimplementedCarrelTestServiceServer() {}

// UnsafeCarrelTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarrelTestServiceServer will
// result in compilation errors.
type UnsafeCarrelTestServiceServer interface {
	mustEmbedUnimplementedCarrelTestServiceServer()
}

func RegisterCarrelTestServiceServer(s grpc.ServiceRegistrar, srv CarrelTestServiceServer) {
	s.RegisterService(&CarrelTestService_ServiceDesc, srv)
}

func _CarrelTestService_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarrelTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarrelTestServiceServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/carrel.test_proto.CarrelTestService/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarrelTestServiceServer).Test(ctx, req.(*CarrelTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CarrelTestService_ServiceDesc is the grpc.ServiceDesc for CarrelTestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CarrelTestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "carrel.test_proto.CarrelTestService",
	HandlerType: (*CarrelTestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _CarrelTestService_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test_prof.proto",
}
