// @generated by protoc-gen-es v0.1.1 with parameter "target=ts"
// @generated from file carrel/constant/supported_text_file/v1/supported_text_file_v1.proto (package carrel.constant.supported_text_file.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from enum carrel.constant.supported_text_file.v1.SupportedTextFile
 */
export enum SupportedTextFile {
  /**
   * @generated from enum value: SUPPORTED_TEXT_FILE_TXT_UNSPECIFIED = 0;
   */
  TXT_UNSPECIFIED = 0,

  /**
   * @generated from enum value: SUPPORTED_TEXT_FILE_MARKDOWN = 1;
   */
  MARKDOWN = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(SupportedTextFile)
proto3.util.setEnumType(SupportedTextFile, "carrel.constant.supported_text_file.v1.SupportedTextFile", [
  { no: 0, name: "SUPPORTED_TEXT_FILE_TXT_UNSPECIFIED" },
  { no: 1, name: "SUPPORTED_TEXT_FILE_MARKDOWN" },
]);

