[package]
name = "stacks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tantivy = "0.18.0"
carrel_commons = { path = "../carrel_commons" }
uuid= "1.1.2"
retry = "2.0.0"
tokio = { version = "1.0.2", features = ["full"] }
serde_json = "1.0.85"
[dev-dependencies]
carrel_utils = { path = "../carrel/carrel_utils" }
