[package]
name = "diji"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default= ["controls", "controls-enigo"]
controls= []
controls-enigo = ["enigo"]
controls-win = ["windows"]

[dependencies]
enigo = { git = "https://github.com/boan-anbo/enigo.git", optional = true }

[dependencies.windows]
version = "0.41.0"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    #    My features
    "Win32_UI_Input_KeyboardAndMouse"
]
optional = true
