// @generated by protoc-gen-es v0.1.1 with parameter "target=ts"
// @generated from file carrel/common/directory/v1/directory_v1.proto (package carrel.common.directory.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type {BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage} from "@bufbuild/protobuf";
import {Message, proto3} from "@bufbuild/protobuf";
import {File} from "../../file/v1/file_v1_pb.js";

/**
 * @generated from message carrel.common.directory.v1.Directory
 */
export class Directory extends Message<Directory> {
  /**
   * @generated from field: string uuid = 2;
   */
  uuid = "";

  /**
   * description
   *
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * directory name
   *
   * @generated from field: string name = 4;
   */
  name = "";

  /**
   * diretory full path
   *
   * @generated from field: string full_path = 8;
   */
  fullPath = "";

  /**
   * @generated from field: string created_at = 9;
   */
  createdAt = "";

  /**
   * @generated from field: string modified_at = 10;
   */
  modifiedAt = "";

  /**
   * @generated from field: repeated carrel.common.file.v1.File files = 11;
   */
  files: File[] = [];

  /**
   * @generated from field: repeated carrel.common.directory.v1.Directory sub_dirs = 12;
   */
  subDirs: Directory[] = [];

  constructor(data?: PartialMessage<Directory>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "carrel.common.directory.v1.Directory";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "full_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "created_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "modified_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "files", kind: "message", T: File, repeated: true },
    { no: 12, name: "sub_dirs", kind: "message", T: Directory, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Directory {
    return new Directory().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Directory {
    return new Directory().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Directory {
    return new Directory().fromJsonString(jsonString, options);
  }

  static equals(a: Directory | PlainMessage<Directory> | undefined, b: Directory | PlainMessage<Directory> | undefined): boolean {
    return proto3.util.equals(Directory, a, b);
  }
}

