// @generated by protoc-gen-es v0.1.1 with parameter "target=ts"
// @generated from file carrel/common/importance/v1/importance_v1.proto (package carrel.common.importance.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from enum carrel.common.importance.v1.Importance
 */
export enum Importance {
  /**
   * @generated from enum value: IMPORTANCE_NONE_UNSPECIFIED = 0;
   */
  NONE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: IMPORTANCE_VERY_LOW = 1;
   */
  VERY_LOW = 1,

  /**
   * @generated from enum value: IMPORTANCE_LOW = 2;
   */
  LOW = 2,

  /**
   * @generated from enum value: IMPORTANCE_MEDIUM = 3;
   */
  MEDIUM = 3,

  /**
   * @generated from enum value: IMPORTANCE_HIGH = 4;
   */
  HIGH = 4,

  /**
   * @generated from enum value: IMPORTANCE_VERY_HIGH = 5;
   */
  VERY_HIGH = 5,

  /**
   * @generated from enum value: IMPORTANCE_TOP_IMPORTANCE = 6;
   */
  TOP_IMPORTANCE = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(Importance)
proto3.util.setEnumType(Importance, "carrel.common.importance.v1.Importance", [
  { no: 0, name: "IMPORTANCE_NONE_UNSPECIFIED" },
  { no: 1, name: "IMPORTANCE_VERY_LOW" },
  { no: 2, name: "IMPORTANCE_LOW" },
  { no: 3, name: "IMPORTANCE_MEDIUM" },
  { no: 4, name: "IMPORTANCE_HIGH" },
  { no: 5, name: "IMPORTANCE_VERY_HIGH" },
  { no: 6, name: "IMPORTANCE_TOP_IMPORTANCE" },
]);

