// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=ts"
// @generated from file grpc/health/v1/grpc_health_v1.proto (package grpc.health.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {HealthCheckRequest, HealthCheckResponse} from "./grpc_health_v1_pb";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service grpc.health.v1.Health
 */
export const Health = {
  typeName: "grpc.health.v1.Health",
  methods: {
    /**
     * @generated from rpc grpc.health.v1.Health.Check
     */
    check: {
      name: "Check",
      I: HealthCheckRequest,
      O: HealthCheckResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

