// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=ts"
// @generated from file carrel_scaffold/v1/scaffold.proto (package carrel_scaffold.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {ScaffoldNewProjectRequest, ScaffoldNewProjectResponse} from "./scaffold_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service carrel_scaffold.v1.ScaffoldNewProjectService
 */
export const ScaffoldNewProjectService = {
  typeName: "carrel_scaffold.v1.ScaffoldNewProjectService",
  methods: {
    /**
     * @generated from rpc carrel_scaffold.v1.ScaffoldNewProjectService.ScaffoldNewProject
     */
    scaffoldNewProject: {
      name: "ScaffoldNewProject",
      I: ScaffoldNewProjectRequest,
      O: ScaffoldNewProjectResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

