[package]
name = "distant_core"
version = "0.1.0"
edition = "2018"


[dependencies]
axum = "0.5.15"
futures = "0.3"
prost = "0.11.0"
prost-types = "0.11.1"
bytes = "1.2.1"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenv = "0.15.0"
cargo-watch = "8.1.2"
uuid = { version = "1", features = ["v4"] }

utoipa = { version = "2", git = "https://github.com/juhaku/utoipa", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "2", git = "https://github.com/juhaku/utoipa", features = ["axum"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "^1"
chrono = { version = "0.4", features = ["serde"] }

# es client
distant_es_client = {path = "../distant_es_client"}

[build-dependencies]
prost-build = { version = "0.11.0" }