[package]
name = "carrel_grpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.8.1"
prost = "0.11.0"
tokio = { version = "1.21.1", features = ["macros", "rt-multi-thread"] }
tonic-health = "0.7.1"
tonic-reflection = "0.5.0"
tonic-web = "0.4.0"
tower-http = { version = "0.3.4", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenv = "0.15.0"
carrel_core = { path = "../carrel_core" }

[build-dependencies]
tonic-build = "0.8.0"
