//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

pub use super::tag::Entity as Tag;
pub use super::tag_relation::Entity as TagRelation;
pub use super::textual_objects::Entity as TextualObjects;
