//! SeaORM Entity. Generated by sea-to_db-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "textual_objects")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uuid: String,
    pub ticket_id: String,
    pub ticket_minimal: String,
    pub source_id: String,
    pub source_name: String,
    pub source_id_type: String,
    pub source_path: String,
    pub store_info: String,
    pub store_url: String,
    pub created: String,
    pub updated: String,
    pub json: String,
    pub json_type: Option<String>,
    pub json_unique_id: Option<String>,
    pub card: String,
    pub card_map: String,
    pub context: String,
    pub ticket_index_in_context: i32,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
