//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "textual_objects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Vec<u8>,
    pub ticket_id: String,
    pub ticket_minimal: String,
    pub source_id: String,
    pub source_name: String,
    pub source_id_type: String,
    pub source_path: String,
    pub store_info: String,
    pub store_url: String,
    pub created: DateTimeUtc,
    pub updated: DateTimeUtc,
    pub json: Vec<u8>,
    pub card: Option<Vec<u8>>,
    pub card_map: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
