// @generated by protoc-gen-es v0.1.1 with parameter "target=ts"
// @generated from file carrel/common/snippet/v1/snippet_v1.proto (package carrel.common.snippet.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type {BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage} from "@bufbuild/protobuf";
import {Message, proto3} from "@bufbuild/protobuf";
import {File} from "../../file/v1/file_v1_pb";
import {Context} from "../../context/v1/context_v1_pb";

/**
 * describes the location of a snippet of string in a plaintext file.
 *
 * @generated from message carrel.common.snippet.v1.Snippet
 */
export class Snippet extends Message<Snippet> {
  /**
   *
   *
   * @generated from field: string snippet = 1;
   */
  snippet = "";

  /**
   * the line number of the snippet in the file
   *
   * @generated from field: int32 line_number = 2;
   */
  lineNumber = 0;

  /**
   * the column number, starting index, of the snippet in the file
   *
   * @generated from field: int32 column_number = 3;
   */
  columnNumber = 0;

  /**
   * the length of the snippet
   *
   * @generated from field: int32 length = 4;
   */
  length = 0;

  /**
   * the file that contains the snippet
   *
   * @generated from field: carrel.common.file.v1.File file = 5;
   */
  file?: File;

  /**
   * the context of the snippet
   *
   * @generated from field: carrel.common.context.v1.Context context = 6;
   */
  context?: Context;

  constructor(data?: PartialMessage<Snippet>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "carrel.common.snippet.v1.Snippet";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "snippet", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "line_number", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "column_number", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "length", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "file", kind: "message", T: File },
    { no: 6, name: "context", kind: "message", T: Context },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Snippet {
    return new Snippet().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Snippet {
    return new Snippet().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Snippet {
    return new Snippet().fromJsonString(jsonString, options);
  }

  static equals(a: Snippet | PlainMessage<Snippet> | undefined, b: Snippet | PlainMessage<Snippet> | undefined): boolean {
    return proto3.util.equals(Snippet, a, b);
  }
}

