import { PlainMessage } from "@bufbuild/protobuf";
import { ListFirefliesByTagResponse } from "../../../../../../backend/carrel_server_client/carrel/server/project_manager/v1/server_project_manager_v1_pb";

export const sampleListFirefliesByTags: PlainMessage<ListFirefliesByTagResponse> = {
    "projectDirectory": "C:\\Script\\carrel\\packages\\carrel\\carrel_desktop\\test\\fixtures\\simple_project",
    "fireflies": [
        {
            "uuid": "12d47c57-22ce-4478-aaea-b88abdb8546f",
            "title": "",
            "description": "Highlight",
            "light": "ADAPTIVENESS AND EQUILIBRIUM.\r\nBy W. R. ASHBY, M.D.,\r\nSt. Andrew's Hospital, Northampton.",
            "context": "478\r\nADAPTIVENESS AND EQUILIBRIUM.\r\nBy W. R. ASHBY, M.D.,\r\nSt. Andrew's Hospital, Northampton.\r\n(Received February 25, 1940.)\r\nTHE behaviour of animals and man may be approached from many points\r\nof view, but there is one feature of their behaviour which is outstanding in\r\nits importance and in its difficulty. I refer to the peculiar â€˜¿\u0003â€˜¿\u0003adaptivenessâ€•\r\nof animals' behaviour. The concept is vague, but everyone knows, roughly at\r\nleast, what is meant by it. It is certainly one of the most remarkable features\r\nof animal behaviour. In psychiatry its importance is central, for it is precisely\r\nthe loss of this â€œ¿\u0003adaptiveness â€œ¿\u0003which is the reason for certification.\r\nWe may demonstrate the phenomenon very clearly by writing, not â€˜¿\u0003â€˜¿\u0003the\r\nburnt child dreads the fire,â€• but â€œ¿\u0003the burnt child seeks the fire.â€• In this\r\nlatter statement we see at once that the adaptiveness has disappeared.\r\nBut the concept of â€œ¿\u0003adaptiveness,â€• though important, has several marked\r\ndisadvantages. Firstly it is vague. It is very difficult to define exactly what\r\nwe mean by the word. Secondly it is not quantitative ; and although one\r\ncan recognize, roughly, degrees of adaptation yet there is, at present, no means\r\nof expressing this quantitatively. Its third disadvantage is that it is apt to\r\ninvolve subjective elements from the mind of the observer. Instead of the\r\nquestion of â€œ¿\u0003adaptiveness â€œ¿\u0003being decided purely by an objective examination\r\nof the animal and its circumstances, it is apt to be a judgment on the part of\r\nthe observer, and there is no guarantee that different observers will all come to\r\nthe same conclusion.\r\nIt would clearly be better if this concept could be changed for another\r\nwhich would be equivalent to it as far as its essential features are concerned\r\nbut which would be free from these objections.\r\nIt is suggested in this paper that the concept of â€œ¿\u0003stableequilibriumâ€• may\r\nperhaps be equivalent to it.\r\nIn order to discuss the question adequately, however, we must first study\r\nthequestionofâ€œ¿\u0003equilibriumâ€•inore detail,forthereismore inthesubject\r\nthan meets the eye.",
            "fullText": "",
            "comment": "[[Summary]]\r\n\r\nRelevant. The first published record of the translation of animal adaptation to the idea of \"stable equilibrium\" between animal and environment.\r\n\r\nShows where his 1945 piece which extends this further to the human and to include trial-and-error as the key feature of adaptiveness came from. Further proof for the animal studies to machine learning transition.\r\n\r\n",
            "commentAuthor": "Bo",
            "commentCreatedAt": "2022-07-17T17:01:57+05:00",
            "commentModifiedAt": "2022-07-17T17:03:45+05:00",
            "importance": 0,
            "locationActual": "0",
            "locationActualType": "pdf_page_index",
            "locationRaw": "0",
            "locationRawType": "pdf_page_index",
            "documentTitle": "[R] [[AshAdaptiveness40]] AshbyW - 1940 - Adaptiveness and Equilibrium",
            "documentDescription": "",
            "documentReference": "",
            "documentPublicationYear": 0,
            "documentPublicationDatetime": "",
            "documentAuthor": "",
            "documentMetadata": {},
            "documentId": "",
            "documentIdType": "",
            "documentStorageId": "",
            "documentStorageIdType": "",
            "documentStorageUrl": "",
            "fileDirectory": "\\\\?\\D:\\Dropbox\\NEra\\New_Core_Reading",
            "fileFullName": "[R] [[AshAdaptiveness40]] AshbyW - 1940 - Adaptiveness and Equilibrium.pdf",
            "fileExtension": "pdf",
            "fileFullPath": "",
            "selectTag": {
                "key": "summary",
                "rawTagString": "[[summary]]",
                "uuid": "7821ce61-8af6-4ac7-afb2-94cf4faed21e",
                "collectionUuids": [],
                "relatedTagUuids": []
            },
            "tags": [
                {
                    "key": "summary",
                    "rawTagString": "[[summary]]",
                    "uuid": "5dda0484-a952-4a1b-86ff-77f262d7ee23",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 16,
                    "parentUuid": "12d47c57-22ce-4478-aaea-b88abdb8546f"
                }
            ],
            "storageIdStr": "",
            "storageIdInt": 0,
            "storageDescription": "",
            "storageUrl": "",
            "createdAt": "2022-07-17T17:01:57+05:00",
            "modifiedAt": "2022-07-17T17:03:45+05:00",
            "extractedAt": "2022-10-18T20:53:07.605203400+00:00",
            "viewedAt": "",
            "collectionUuids": [],
            "metadata": {},
            "moreComments": {},
            "locationActualModifiedAt": "2022-10-18T20:53:07.605203400+00:00",
            "documentPages": 7,
            "uniqueId": ""
        },
        {
            "uuid": "1cdb0505-fc6c-43fc-b094-281d434c2d85",
            "title": "",
            "description": "Underline",
            "light": " SOME DETERMINING FACTORS IN MAZE-PERFORMANCE",
            "context": " NOTES AND DISCUSSIONS 315\r\n organization is dynamically constituted in tim\r\n ative, realizing no doubt the vagueness of th\r\n physiological hypothesis to inflate its frail fabri\r\n be sympathetic. Every psychologist who has at\r\n ness has come up against this problem. And w\r\n recognition of the problem of the gross phenomen\r\n unconscious inference, apperception, attention, \r\n instinct, purpose, drive, conation, and now insig\r\n one bit further along.\r\n When one considers the book as a whole, one s\r\n from assurance at the beginning to incertitude \r\n are but little polemical, and I have nothing bu\r\n candor in thinking aloud and in exposing hypo\r\n This is Gestalt psychology as psychology and \r\n find this spirit in the earlier chapters where th\r\n dummy antagonists. That, I think, is Gestalt \r\n there are really two such different Gestalt psycho\r\n double personality has been received with such m\r\n Harvard University EDWIN G. BORING\r\n 14\"There they stood ranged along the hill-sides! .\r\n slug-horn to my lips I set and blew.\" Poetical quota\r\n but the picture that I have in mind is given by the \r\n Childe Roland to the Dark Tower Came.\r\n SOME DETERMINING FACTORS IN MAZE-PERFORMANCE\r\n As a result of experiments on animal learning a great deal of attention has\r\n been paid to the establishment of the conditions which underlie efficient maze-\r\n performance. The conditions are complex and writers have tended to emphasize\r\n one condition or another without-so it seems to the present writer-gaining a\r\n satisfactory picture of the various interrelationships involved.'\r\n Among the factors which determine efficient maze-performance it is possible\r\n to distinguish at least three primary variables: 'knowledge,' 'reward,' and\r\n 'drive.' There is also a secondary variable, 'reward-value,'2 which is dependent\r\n upon all three of these. Let us then examine these variables and see how they\r\n are related to maze-performance and to each other.\r\n Knowledge is a requisite for efficient maze-performance. The rat must\r\n 'know' the maze if he is to traverse it rapidly and with a minimum of errors.\r\n And here we should note that the usual 'learning' experiment deals only with\r\n this relationship, measuring knowledge in terms of maze-performance. Blod-\r\n 'Professor Tolman has referred to the present analysis in a paper read at\r\n The Ninth International Congress of Psychology at New Haven, September 6,\r\n 1929. See E. C. Tolman, Maze-performance as a function of motivation and\r\n of reward as well as of knowledge of maze-paths, Proc. IX Internat. Cong.\r\n Psychol., 1929, 439f.\r\n 2The term 'reward-value' has been used with a slightly more limited meaning\r\n by Katherine A. Williams.\r\nThis content downloaded from\r\n128.36.7.166 on Sun, 10 Jul 2022 00:42:43 UTC",
            "fullText": "",
            "comment": "Relevant. Tolman credit his distinction between performance and learning to MN Elliott, such as shown in this piece which came out around the same time as Tolman's Purposive Behavior in Animal and Man. Also useful is the diagram for the relations among reward, learning, performance, drive, and reward-value. Reward-value corresponds to the same concept in RL?\r\n\r\n[[Summary]]",
            "commentAuthor": "Bo",
            "commentCreatedAt": "2022-07-09T22:36:22+05:00",
            "commentModifiedAt": "2022-07-09T22:37:51+05:00",
            "importance": 0,
            "locationActual": "1",
            "locationActualType": "pdf_page_index",
            "locationRaw": "1",
            "locationRawType": "pdf_page_index",
            "documentTitle": "[R] [[EllDetermining30]] ElliottM - 1930 - Some Determining Factors in Maze-Performance",
            "documentDescription": "",
            "documentReference": "",
            "documentPublicationYear": 0,
            "documentPublicationDatetime": "",
            "documentAuthor": "",
            "documentMetadata": {},
            "documentId": "",
            "documentIdType": "",
            "documentStorageId": "",
            "documentStorageIdType": "",
            "documentStorageUrl": "",
            "fileDirectory": "\\\\?\\D:\\Dropbox\\NEra\\New_Core_Reading",
            "fileFullName": "[R] [[EllDetermining30]] ElliottM - 1930 - Some Determining Factors in Maze-Performance.pdf",
            "fileExtension": "pdf",
            "fileFullPath": "",
            "selectTag": {
                "key": "summary",
                "rawTagString": "[[summary]]",
                "uuid": "7d1fd8b8-ae60-4da4-9155-8fb149399b66",
                "collectionUuids": [],
                "relatedTagUuids": []
            },
            "tags": [
                {
                    "key": "summary",
                    "rawTagString": "[[summary]]",
                    "uuid": "f252b0de-d3b8-446b-8558-29cf833ad0e8",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 137,
                    "parentUuid": "1cdb0505-fc6c-43fc-b094-281d434c2d85"
                }
            ],
            "storageIdStr": "",
            "storageIdInt": 0,
            "storageDescription": "",
            "storageUrl": "",
            "createdAt": "2022-07-09T22:36:22+05:00",
            "modifiedAt": "2022-07-09T22:37:51+05:00",
            "extractedAt": "2022-10-18T23:32:32.002142400+00:00",
            "viewedAt": "",
            "collectionUuids": [],
            "metadata": {},
            "moreComments": {},
            "locationActualModifiedAt": "2022-10-18T23:32:32.002142400+00:00",
            "documentPages": 4,
            "uniqueId": ""
        },
        {
            "uuid": "1e21ae38-5106-4375-9ec2-fb0f44ed466c",
            "title": "",
            "description": "Highlight",
            "light": "The Mind \r\nand its Place in Nature ",
            "context": "International Library of Psychology \r\nPhilosophy and Scientific Method \r\nThe Mind \r\nand its Place in Nature ",
            "fullText": "",
            "comment": "Relevant. A series of lectures where Tolman's molar and molecular behaviorism distinction come from. Here both positions are criticized by the author, but Tolman used the molar behaviorism where behavior is treated as a whole rather than a mere sum of physiological parts, a good version of behaviorism.\r\n\r\n[[Summary]]",
            "commentAuthor": "Bo",
            "commentCreatedAt": "2022-07-09T22:00:55+05:00",
            "commentModifiedAt": "2022-07-09T22:02:42+05:00",
            "importance": 0,
            "locationActual": "0",
            "locationActualType": "pdf_page_index",
            "locationRaw": "0",
            "locationRawType": "pdf_page_index",
            "documentTitle": "[R] [[BroMind25]] BroadC - 1925 - The mind and its place in nature",
            "documentDescription": "",
            "documentReference": "",
            "documentPublicationYear": 0,
            "documentPublicationDatetime": "",
            "documentAuthor": "",
            "documentMetadata": {},
            "documentId": "",
            "documentIdType": "",
            "documentStorageId": "",
            "documentStorageIdType": "",
            "documentStorageUrl": "",
            "fileDirectory": "\\\\?\\D:\\Dropbox\\NEra\\New_Core_Reading",
            "fileFullName": "[R] [[BroMind25]] BroadC - 1925 - The mind and its place in nature.pdf",
            "fileExtension": "pdf",
            "fileFullPath": "",
            "selectTag": {
                "key": "summary",
                "rawTagString": "[[summary]]",
                "uuid": "301a7bb0-478b-4b7a-ba7a-b8d7091ffd0f",
                "collectionUuids": [],
                "relatedTagUuids": []
            },
            "tags": [
                {
                    "key": "summary",
                    "rawTagString": "[[summary]]",
                    "uuid": "11ba501e-bec8-400c-b3c8-7f6a7f9d391f",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 71,
                    "parentUuid": "1e21ae38-5106-4375-9ec2-fb0f44ed466c"
                }
            ],
            "storageIdStr": "",
            "storageIdInt": 0,
            "storageDescription": "",
            "storageUrl": "",
            "createdAt": "2022-07-09T22:00:55+05:00",
            "modifiedAt": "2022-07-09T22:02:42+05:00",
            "extractedAt": "2022-10-18T21:22:14.844951200+00:00",
            "viewedAt": "",
            "collectionUuids": [],
            "metadata": {},
            "moreComments": {},
            "locationActualModifiedAt": "2022-10-18T21:22:14.844951200+00:00",
            "documentPages": 684,
            "uniqueId": ""
        },
        {
            "uuid": "23b40748-00d0-4a56-9b98-256de3e0849e",
            "title": "",
            "description": "Highlight",
            "light": "THE JOURNAL OF PHILOSOPHY \r\nPSYCHOLOGY AND SCIENTIFIC METHODS ",
            "context": "VOL. XIII, No. 20. SEPTEMBER 28, 1916 \r\nTHE JOURNAL OF PHILOSOPHY \r\nPSYCHOLOGY AND SCIENTIFIC METHODS \r\nSENSATION AND PERCEPTION \r\nI. THE GENETIC RELATIONSHIP \r\nA S present-day psychology conceives it, the sensation is one, per\u0002haps the most important, of the elementary conscious proc\u0002esses. It marks the limit, at least in one direction, to which we can \r\ncarry our introspective analysis of the contents of consciousness. \r\nIn the adult the sensation occurs always in combination. One never \r\nexperiences sensations which are not structural elements in percep\u0002tions or other complexes. Colors, for example, are seen as the colors \r\nof or on things; the tones are elements in voices or other complex \r\nsounds, or, at least, they are heard as coming from a certain direc\u0002tion; the cutaneous sensations are the consistencies and temperatures \r\nof hard or soft, warm or cold, things; etc. It is possible, however, by \r\nintrospection to analyze out the simple sensations which go to make \r\nup, say, our percept of a red paper disc, and to attend merely to the \r\nred color. By such means we can study the sensation itself and ob\u0002serve the characteristic changes it undergoes. As the psychologist \r\nis at pains to point out, the sensation thus isolated by attention has \r\nipso facto undergone certain changes of attribute. As an elementary \r\nconstituent of the complex percept, it is, he says, an artifact, an ab\u0002straction, whose characteristics in the limbo of inattention can only \r\nbe assumed. Some of the difficulties of this conception I have dis\u0002cussed in a former article.1 \r\nBut the sensation is not regarded merely as an analytic element, \r\nbut as a genetic element as well. While certain of the more careful \r\nanalytic psychologists, like Professor Titchener, for example, are at \r\npains to discriminate between the analytically simple and the gen\u0002etically prior, and to point out that the elements reached by analytic \r\nintrospection of adult consciousness are not to be taken as genetic \r\nelements, it is nevertheless true that the sensation does figure very \r\nwidely as genetically primary. Experience of sensory qualities is \r\nput first in the development and is the prius from which the complex \r\n1 \" ' The Psychological Element, \" The Philosophicat Review, July, 1915. \r\n533 ",
            "fullText": "",
            "comment": "A less-well know thinker but critical influence on Tolman and others. In this and a part two of this piece, Laguna that criticized the reductivism in the kind of behaviorism that was influenced by British empiricism and associationism (such as Thorndike and Watson). Two key contributions in this critical piece are: (1) sensations are not building blocks of perceptions which are always in situation and about objects, such as Laguna's example of eating breakfast is different from seeing colors of the chair and feeling warmth of the food; and (2) the idea of simplicity meaning foundational has ideological consequence. I'm quoting her insightful internalist critique in full: \" analytic simplicity was frankly identified with genetic primacy, applied in political science, it led to individualism and the social contract theory; applied in ethics, it produced the hedonism of the eighteenth century, in which happiness was supposed to be built up out of atomic increments of pleasure; applied in logic,\r\nit resulted in the well-known theory that judgments come after concepts and are made out of them, while judgments in turn are put together to form syllogisms.\"\r\n\r\nIt's telling that Tolman was quoting her prominently since the beginning and her position gives us hint as to Tolman's ideology.\r\n\r\n[[Point]][[Summary]]",
            "commentAuthor": "Bo",
            "commentCreatedAt": "2022-07-12T23:07:01+05:00",
            "commentModifiedAt": "2022-07-12T23:12:52+05:00",
            "importance": 0,
            "locationActual": "1",
            "locationActualType": "pdf_page_index",
            "locationRaw": "1",
            "locationRawType": "pdf_page_index",
            "documentTitle": "[R] [[deSensation16a]] de LagunaG - 1916 - Sensation and Perception - I - The Genetic Relationship",
            "documentDescription": "",
            "documentReference": "",
            "documentPublicationYear": 0,
            "documentPublicationDatetime": "",
            "documentAuthor": "",
            "documentMetadata": {},
            "documentId": "",
            "documentIdType": "",
            "documentStorageId": "",
            "documentStorageIdType": "",
            "documentStorageUrl": "",
            "fileDirectory": "\\\\?\\D:\\Dropbox\\NEra\\New_Core_Reading",
            "fileFullName": "[R] [[deSensation16a]] de LagunaG - 1916 - Sensation and Perception - I - The Genetic Relationship.pdf",
            "fileExtension": "pdf",
            "fileFullPath": "",
            "selectTag": {
                "key": "point",
                "rawTagString": "[[point]]",
                "uuid": "010a09a6-64b3-4c1c-8fdd-79c3dfe3d714",
                "collectionUuids": [],
                "relatedTagUuids": []
            },
            "tags": [
                {
                    "key": "point",
                    "rawTagString": "[[point]]",
                    "uuid": "3c40a687-575f-42d3-891a-fea750352780",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 109,
                    "parentUuid": "23b40748-00d0-4a56-9b98-256de3e0849e"
                },
                {
                    "key": "summary",
                    "rawTagString": "[[summary]]",
                    "uuid": "21fea70a-b2d9-42bd-8a5a-ba89f08a1396",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 110,
                    "parentUuid": "23b40748-00d0-4a56-9b98-256de3e0849e"
                }
            ],
            "storageIdStr": "",
            "storageIdInt": 0,
            "storageDescription": "",
            "storageUrl": "",
            "createdAt": "2022-07-12T23:07:01+05:00",
            "modifiedAt": "2022-07-12T23:12:52+05:00",
            "extractedAt": "2022-10-18T23:02:24.137309800+00:00",
            "viewedAt": "",
            "collectionUuids": [],
            "metadata": {},
            "moreComments": {},
            "locationActualModifiedAt": "2022-10-18T23:02:24.137309800+00:00",
            "documentPages": 16,
            "uniqueId": ""
        },
        {
            "uuid": "4331b195-9798-4b4a-81c6-09dc210f1449",
            "title": "",
            "description": "Highlight",
            "light": "The Journal of General Psychology, 1945, 32, 13-25. \r\nTHE PHYSICAL ORIGIN OF ADAPTATION BY TRIAL AND \r\nERROR* ",
            "context": "The Journal of General Psychology, 1945, 32, 13-25. \r\nTHE PHYSICAL ORIGIN OF ADAPTATION BY TRIAL AND \r\nERROR* \r\nNorthampton, England \r\nW. R. AsHBY \r\nA. INTRODUCTION \r\nThe type of behavior known as \"adaptation by trial and error\" is of \r\nwide occurrence, being demonstrable with most ciarity and simplicity in the \r\nlower organisms. \r\nIt is the purpose of this paper to suggest that this type of ·behavior is in \r\nno way special to living things, that it is an elementary and fundamental \r\nproperty of all matter, and that it finds its origin and explanation in the \r\nconcept of a machine \"breaking.\" It is demonstrated, that if any environ\u0002ment starts to break down any machine, then that machine is bound to \r\nshow the essential features of adaptation by trial and error, if b}i \"adapta\u0002tion\" we understand \"reaching equilibrium.\" \r\nThe proof proceeds in three stages: First it is shown that \"adapted\" from \r\nthe physiological point of view is equivalent to \"in equilibrium\" from the \r\nphysical point of view, at least in the simpler cases. Secondly, it is shown \r\nthat all dynamic systems, whether living or dead, keep breaking until they \r\nreach some equilibrium, reaching it by a process identical with that of trial \r\nand error. (So far no special hypothesis is required). Thirdly, if we add \r\nthe hypothesis that the breaks are available in large numbers and are con\u0002sistent, then it is shown that the machine is bound automatically to reach \r\nan equilibrium within certain essential limits. \r\nA difficulty of much psychological theorizing is vagueness in the terms \r\nemployed. In this work, the above ideas have been studied in mathematical \r\nform throughout, the definitions and proofs being given corresponding \r\nprecision. \r\nB. ADAPTATION BY TRIAL AND ERROR \r\nWe must first be agreed on the essential features of this mode of behavior. \r\nThey seem to be as follows (listed here for convenience) : ( 1 ) It is called \r\nforth only when the environment becomes in some way unsatisfactory. (2) \r\n*Received in the Editorial Office on June 12, 1943. \r\n13 ",
            "fullText": "",
            "comment": "[[IMPORTANCE|ESSENTIAL]][[Summary]]\r\n\r\nKey source that connects animal learning with cybernetics. Influenced (and influenced by) Norbert Wiener, Marvin Minsky, and other AI and machine learning pioneers.\r\n\r\nKey ideas include:\r\n1. breaking is not (in the last instance) hazardous to the \"organism\", but necessary step towards adaptation aka maintaining equilibrium.\r\n\r\n2. Adaptation through trial-and-error, therefore, is essential property of the \"matter\".\r\n\r\n3. [Similar to behaviorism], no \"vital\" or \"selective\" hypothesis is required. i.e. no need to consider the internal quality, purpose, or livining & non-living distinctions.\r\n\r\nHe was citing people like Jennings and made a super clear hypothesis that those characters of learning Jennings found in \"lower\" organisms is foundamental to \"all matter\". \r\n\r\nThis piece shows clearly how cybernetics took over from early behaviorism (this is written in 1943) and animal learning and prepared a reformulation in terms of self-equilibrium via environmental exchanges for machine learning. The use of mathematical formula is also significant for the \"theoretical translation\" Ashby done between psychology and AI.",
            "commentAuthor": "Bo",
            "commentCreatedAt": "2022-07-17T16:15:16+05:00",
            "commentModifiedAt": "2022-07-17T16:19:35+05:00",
            "importance": 0,
            "locationActual": "1",
            "locationActualType": "pdf_page_index",
            "locationRaw": "1",
            "locationRawType": "pdf_page_index",
            "documentTitle": "[R] [[AshPhysical45]] AshbyW - 1945 - The Physical Origin of Adaptation by Trial and Error",
            "documentDescription": "",
            "documentReference": "",
            "documentPublicationYear": 0,
            "documentPublicationDatetime": "",
            "documentAuthor": "",
            "documentMetadata": {},
            "documentId": "",
            "documentIdType": "",
            "documentStorageId": "",
            "documentStorageIdType": "",
            "documentStorageUrl": "",
            "fileDirectory": "\\\\?\\D:\\Dropbox\\NEra\\New_Core_Reading",
            "fileFullName": "[R] [[AshPhysical45]] AshbyW - 1945 - The Physical Origin of Adaptation by Trial and Error.pdf",
            "fileExtension": "pdf",
            "fileFullPath": "",
            "selectTag": {
                "key": "importance",
                "value": "ESSENTIAL",
                "rawTagString": "[[importance|essential]]",
                "uuid": "411b198f-aaa4-4c97-bde7-9ac5e4b97da2",
                "collectionUuids": [],
                "relatedTagUuids": []
            },
            "tags": [
                {
                    "key": "importance",
                    "value": "essential",
                    "rawTagString": "[[importance|essential]]",
                    "uuid": "b25b4c61-b394-408c-bcc1-a56939a4c0b7",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 18,
                    "parentUuid": "4331b195-9798-4b4a-81c6-09dc210f1449"
                },
                {
                    "key": "summary",
                    "rawTagString": "[[summary]]",
                    "uuid": "1f7177fc-e0e4-42d9-b8cc-df16a1153eaa",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 19,
                    "parentUuid": "4331b195-9798-4b4a-81c6-09dc210f1449"
                }
            ],
            "storageIdStr": "",
            "storageIdInt": 0,
            "storageDescription": "",
            "storageUrl": "",
            "createdAt": "2022-07-17T16:15:16+05:00",
            "modifiedAt": "2022-07-17T16:19:35+05:00",
            "extractedAt": "2022-10-18T20:53:14.777665300+00:00",
            "viewedAt": "",
            "collectionUuids": [],
            "metadata": {},
            "moreComments": {},
            "locationActualModifiedAt": "2022-10-18T20:53:14.777665300+00:00",
            "documentPages": 14,
            "uniqueId": ""
        },
        {
            "uuid": "5daa39d2-190b-4e7f-97f8-7de1f95ad408",
            "title": "",
            "description": "Highlight",
            "light": "SIMULATION OF SELF-ORGANIZING SYSTEMS BY DIGITAL COMPUTER*\r\nB. G. Farley and. W. A. Clark\r\nLincoln Laboratory, Massachusetts Institute of Technology\r\nCambridge, Massachusetts\r\nABSTRACT",
            "context": "SIMULATION OF SELF-ORGANIZING SYSTEMS BY DIGITAL COMPUTER*\r\nB. G. Farley and. W. A. Clark\r\nLincoln Laboratory, Massachusetts Institute of Technology\r\nCambridge, Massachusetts\r\nABSTRACT\r\nA general discussion of ideas and definitions relating to self-organizing systems and their synthesis is\r\ngiven, together with remarks concerning their simulation by digital computer. Synthesis and simulation\r\nof an actual system is then described. This system, initially randomly organized within wide limits,\r\norganizes itself to perform a simple prescribed task.\r\nINTRODUCTION\r\nInformation systems whose response to a given class of inputs changes with time in accordance\r\nwith specified criteria which are chosen to correspond roughly to the “self-organizing\" concept have\r\nbeen the.subject of considerable interest.7,la Several mechanisms have beenconstrueted or described which are,\r\n\"self-organizing\" to some extent,1 ’®’8’\r\n1\r\n’and some work has been published on computer-programmed learn¬\r\ning, such as that by Oettinger.5 Recently, McKay has communicated ideas related to some of those to be\r\ndiscussed here.4\r\nThe work to be described was undertaken in an attempt to clarify certain ideas related to such\r\nsystems, and to try to gain some insight into their synthesis by simulation of specific systems using a\r\ndigital computer. Although the work is in an early stage, it is believed that results so far have ex¬\r\nhibited some very Interesting properties of a particular system, and have demonstrated the usefulness of\r\ncomputer simulation methods in studies of this kind where systems are likely to be so complex that ana¬\r\nlytical solutions are difficult or impossible, or do not furnish much information until leads are sug¬\r\ngested by actual experience.\r\nThe work will be presented in three parts. First a general discussion will be given in which\r\ndefinitions will be made. Second, the definitions will be applied to an experimental system. Third, the\r\ndetails of a self-organizing system and a description of computer techniques used in its simulation will\r\nbe given.\r\nGeneral Considerations and Definitions\r\nIn order to make our ideas and definitions precise, and at the same time as general as possible,\r\nit is convenient to introduce a mathematical framework to aid in discussion.\r\nWe will deal first with a general systemes shown in Figure 1. Inputs p, from the left are trans¬\r\nformed into outputs q. on the right. As indicated in Figure 1, both input and output lines may be\r\nmultiple. In what follows, the symbols p, and q. will refer to specific, complete configurations on\r\nthese multiple lines, finite or infinite in time. No loss of generality will result if all signals are\r\nreduced to a binary equivalent. As an example, then, if there are three input lines, a certain input\r\nmight be defined as\r\n{\r\n0110001011001...\r\n1001101011001\r\n0110101000000\r\ntime increasing to the right. Such a configuration will be called a time-channel pattern.\r\nThe transformation T will be allowed to change with time,\r\nin so far as it exhibits organizing properties with respect to T.\r\nwill fix our attention on a particular class C of inputs p~,l,2,.\r\nEach member of this class will usually be finite in length?\r\nand we are interested in this change\r\nTo define properties of this type we\r\n..,n and their corresponding outputs q,.\r\nJ\r\nWe may then break the transformation T down into a class of transforms\r\nT = ,\r\n*The research in this document was supported\r\nthe Massachusetts Institute of Technology.\r\nTa, (2)\r\njointly by the Army, Navy, and Air Force under contract with\r\n76",
            "fullText": "",
            "comment": "Relevant. A work that according to Barto 2019 was the first to implement Turing's child machine idea, while in fact this article was citing an earlier one by Oettinger which was consciously modeled after Turing's idea. \r\n\r\nBesides being one of the earliest to implemement a RL model on digital computer--which they framed as a transformation from unorganized to organized systems through modifiers, the citation of thie articles shows clearly the importance of Turing and the Radio club on early AI in the US.\r\n\r\n[[IMPORTANCE|RELEVANT]]\r\n[[Summary]]",
            "commentAuthor": "Bo",
            "commentCreatedAt": "2022-07-23T23:08:33+05:00",
            "commentModifiedAt": "2022-07-23T23:11:51+05:00",
            "importance": 0,
            "locationActual": "0",
            "locationActualType": "pdf_page_index",
            "locationRaw": "0",
            "locationRawType": "pdf_page_index",
            "documentTitle": "[R] [[FCSimulation54]] FarleyB, ClarkW - 1954 - Simulation of self-organizing systems by digital computer",
            "documentDescription": "",
            "documentReference": "",
            "documentPublicationYear": 0,
            "documentPublicationDatetime": "",
            "documentAuthor": "",
            "documentMetadata": {},
            "documentId": "",
            "documentIdType": "",
            "documentStorageId": "",
            "documentStorageIdType": "",
            "documentStorageUrl": "",
            "fileDirectory": "\\\\?\\D:\\Dropbox\\NEra\\New_Core_Reading",
            "fileFullName": "[R] [[FCSimulation54]] FarleyB, ClarkW - 1954 - Simulation of self-organizing systems by digital computer.pdf",
            "fileExtension": "pdf",
            "fileFullPath": "",
            "selectTag": {
                "key": "importance",
                "value": "RELEVANT",
                "rawTagString": "[[importance|relevant]]",
                "uuid": "f9f1eb10-7a6b-444a-9930-9f73bfa969dc",
                "collectionUuids": [],
                "relatedTagUuids": []
            },
            "tags": [
                {
                    "key": "importance",
                    "value": "relevant",
                    "rawTagString": "[[importance|relevant]]",
                    "uuid": "3d333601-335f-4ac1-89a8-ff4d2762841c",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 138,
                    "parentUuid": "5daa39d2-190b-4e7f-97f8-7de1f95ad408"
                },
                {
                    "key": "summary",
                    "rawTagString": "[[summary]]",
                    "uuid": "d1bdabdd-50b6-441a-ac28-488b677ffdad",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 139,
                    "parentUuid": "5daa39d2-190b-4e7f-97f8-7de1f95ad408"
                }
            ],
            "storageIdStr": "",
            "storageIdInt": 0,
            "storageDescription": "",
            "storageUrl": "",
            "createdAt": "2022-07-23T23:08:33+05:00",
            "modifiedAt": "2022-07-23T23:11:51+05:00",
            "extractedAt": "2022-10-18T23:49:53.559437600+00:00",
            "viewedAt": "",
            "collectionUuids": [],
            "metadata": {},
            "moreComments": {},
            "locationActualModifiedAt": "2022-10-18T23:49:53.559437600+00:00",
            "documentPages": 9,
            "uniqueId": ""
        },
        {
            "uuid": "68a57655-eeda-4e35-991c-9d91899da3e7",
            "title": "",
            "description": "Highlight",
            "light": "SIMPLE TRIAL-AND-ERROR LEARNING: A STUDY\r\nIN PSYCHOLOGICAL THEORY\r\nBY CLARK L. HULL\r\nInstitute of Human Relations, Yale University",
            "context": "SIMPLE TRIAL-AND-ERROR LEARNING: A STUDY\r\nIN PSYCHOLOGICAL THEORY\r\nBY CLARK L. HULL\r\nInstitute of Human Relations, Yale University\r\nI\r\nScience proceeds by a double movement. For the most\r\npart, scientific discoveries are accomplished by means of\r\nobservation and experiment. Occasionally, however, it hap\u0002pens that a discovery is made by means of a more or less\r\ncomplex logical process or 'gedanken experiment.' Einstein's\r\nmathematical deduction and prediction of what may be\r\nobserved in the behavior of light when it passes near the sun\r\nis perhaps as good an example of this as any.\r\nFrequently, after the existence and characteristics of\r\nnatural phenomena have been discovered empirically, it is\r\nseen that these things might very well have been deduced\r\nfrom facts and principles already known. When the deduc\u0002tion is thus performed, as a kind of afterthought, the process\r\nis more properly termed explanation. Actual prediction is\r\nmore dramatic than explanation, but the two processes are\r\nlogically very similar. A true deductive explanation possesses\r\na quality of logical necessity closely akin to prediction regard\u0002less of when the empirical observation takes place. It is of\r\nthe mass of such interlocking deductive explanations that\r\nscientific systems are made. In general, that science is most\r\nperfectly systematized which can show the greatest proportion\r\nof its phenomena as logically deducible from recognized\r\nprinciples and other known phenomena. Moreover it seems\r\nreasonable that rival systems within a science may also be\r\nevaluated on the basis of this same criterion.\r\nIt is evident that much of what passes for explanation\r\nfails of this true deductive quality. It avails little merely to\r\n241",
            "fullText": "",
            "comment": "[[IMPORTANCE|ESSENTIAL]]\r\n[[Summary]]\r\n\r\nSignificant contribution by Hull towards: \r\n\r\n1. showing behavioral psychology is more scientific and capable of producing verifiable and concrete hypothesis, \r\n\r\n2. shows a \"simple\" theory of reinforcement learning where connections change strengths in acquisition or extinction and collectively form larger patterns that are \"intelligent\" in learning, and \r\n\r\n3. arguing that behavioral explanation is reductive enough that we can built a \"psychic\" machine to simulate human intelligence.\r\n\r\n4. He and his collaborator already built such a psychic machine. See the reference at the end of the essay.\r\n\r\nAll of these were impressive considering it was 1929, before Turing's essay, before Skinner's RL, and contemporary to Tolman's approach to \"purpose\" as something observable in behavior.\r\n\r\nIf we want to find one behavioral psychologist to trace AI to, Hull was the one.",
            "commentAuthor": "Bo",
            "commentCreatedAt": "2022-07-24T19:32:30+05:00",
            "commentModifiedAt": "2022-07-24T19:38:07+05:00",
            "importance": 0,
            "locationActual": "0",
            "locationActualType": "pdf_page_index",
            "locationRaw": "0",
            "locationRawType": "pdf_page_index",
            "documentTitle": "[R] [[HulSimple30]] HullC - 1930 - Simple trial and error learning - A study in psychological theory",
            "documentDescription": "",
            "documentReference": "",
            "documentPublicationYear": 0,
            "documentPublicationDatetime": "",
            "documentAuthor": "",
            "documentMetadata": {},
            "documentId": "",
            "documentIdType": "",
            "documentStorageId": "",
            "documentStorageIdType": "",
            "documentStorageUrl": "",
            "fileDirectory": "\\\\?\\D:\\Dropbox\\NEra\\New_Core_Reading",
            "fileFullName": "[R] [[HulSimple30]] HullC - 1930 - Simple trial and error learning - A study in psychological theory.pdf",
            "fileExtension": "pdf",
            "fileFullPath": "",
            "selectTag": {
                "key": "importance",
                "value": "ESSENTIAL",
                "rawTagString": "[[importance|essential]]",
                "uuid": "20320f76-3773-4e9c-a33c-a076e9796b19",
                "collectionUuids": [],
                "relatedTagUuids": []
            },
            "tags": [
                {
                    "key": "importance",
                    "value": "essential",
                    "rawTagString": "[[importance|essential]]",
                    "uuid": "c11808a1-5c92-41b8-b075-ddf4b04b249c",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 164,
                    "parentUuid": "68a57655-eeda-4e35-991c-9d91899da3e7"
                },
                {
                    "key": "summary",
                    "rawTagString": "[[summary]]",
                    "uuid": "853942ae-3295-4b91-9c5b-5bf567737c77",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 165,
                    "parentUuid": "68a57655-eeda-4e35-991c-9d91899da3e7"
                }
            ],
            "storageIdStr": "",
            "storageIdInt": 0,
            "storageDescription": "",
            "storageUrl": "",
            "createdAt": "2022-07-24T19:32:30+05:00",
            "modifiedAt": "2022-07-24T19:38:07+05:00",
            "extractedAt": "2022-10-19T02:47:34.073620600+00:00",
            "viewedAt": "",
            "collectionUuids": [],
            "metadata": {},
            "moreComments": {},
            "locationActualModifiedAt": "2022-10-19T02:47:34.073620600+00:00",
            "documentPages": 16,
            "uniqueId": ""
        },
        {
            "uuid": "6de970b5-858f-45f5-9173-76fadae75208",
            "title": "",
            "description": "Highlight",
            "light": "Brain Function and Adaptive Systems -\r\nA Heterostatic Theory\r\nA. HARRY KLOPF",
            "context": "AFCRL- 72-0164 3 MARCH 1972\r\nSPECIAL REPORTS, NO. 133 R\r\n1\r\nDATA SCIENCES LABORATORY PROJECT 5632\r\nAIR FORCE CAMBRIDGE RESEARCH LABORATORIES\r\nL. G. HANSCOM FIELD, BEDFORD, MASSACHUSETTS\r\nBrain Function and Adaptive Systems -\r\nA Heterostatic Theory\r\nA. HARRY KLOPF\r\nThe research reported herein was accomplished while the author held a\r\nNational Research Council Postdoctoral Resident Research Associateship\r\nsupported by the Air Force Systems Command, United States Air Force.\r\nApproved for public release; distribution unlimited.\r\nAIR FORCE SYSTEMS COMMAND\r\nUnited States Air Force\r\nHAIR\r\nFORCESISMISCOMMANY",
            "fullText": "",
            "comment": "[[Summary]][[IMPORTANCE|ESSENTIAL]]\r\n\r\nEssential piece for the history of RL. Responsible for the \"revival\" of animal learning in RL, if not RL in general, through his influence on Barto and Sutton.\r\n\r\nHe proposed a heterostatic  of neural activity as opposed to the homeostatic theory from Cannon to Ashby to Wiener. In terms of the interpretation of reward, it means the view that reward it NOT for reduction of disruption but a pursuit of an increase of positive--pleasure--results. The experimental basis for these claims are from people like Olds.\r\n\r\nBut note, that it's more of an internal divergence within cybernetic psychology which is an abstracted and mathematical inheritance of behaviorism, not a critique of behaviorism. And there is little mention of internal states as well. \r\n\r\nThis has broad external implications, some of which are speculated by the author, such as the justification of self-interest and individualism which only cooperates on a higher level, such as the nation, when the overall benefits is large enough.",
            "commentAuthor": "Bo",
            "commentCreatedAt": "2022-07-17T19:57:55+05:00",
            "commentModifiedAt": "2022-07-17T20:03:15+05:00",
            "importance": 0,
            "locationActual": "3",
            "locationActualType": "pdf_page_index",
            "locationRaw": "3",
            "locationRawType": "pdf_page_index",
            "documentTitle": "[R] [[KloBrain72]] KlopfA - 1972 - Brain Function and Adaptive Systems - A Heterostatic Theory",
            "documentDescription": "",
            "documentReference": "",
            "documentPublicationYear": 0,
            "documentPublicationDatetime": "",
            "documentAuthor": "",
            "documentMetadata": {},
            "documentId": "",
            "documentIdType": "",
            "documentStorageId": "",
            "documentStorageIdType": "",
            "documentStorageUrl": "",
            "fileDirectory": "\\\\?\\D:\\Dropbox\\NEra\\New_Core_Reading",
            "fileFullName": "[R] [[KloBrain72]] KlopfA - 1972 - Brain Function and Adaptive Systems - A Heterostatic Theory.pdf",
            "fileExtension": "pdf",
            "fileFullPath": "",
            "selectTag": {
                "key": "summary",
                "rawTagString": "[[summary]]",
                "uuid": "8f186c42-5446-4b3d-88c1-99d40a34a72c",
                "collectionUuids": [],
                "relatedTagUuids": []
            },
            "tags": [
                {
                    "key": "summary",
                    "rawTagString": "[[summary]]",
                    "uuid": "5e7e567a-496a-4f41-8462-91e99792c43f",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 178,
                    "parentUuid": "6de970b5-858f-45f5-9173-76fadae75208"
                },
                {
                    "key": "importance",
                    "value": "essential",
                    "rawTagString": "[[importance|essential]]",
                    "uuid": "c31ea5d1-f28f-4717-85c2-2818af0a6412",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 179,
                    "parentUuid": "6de970b5-858f-45f5-9173-76fadae75208"
                }
            ],
            "storageIdStr": "",
            "storageIdInt": 0,
            "storageDescription": "",
            "storageUrl": "",
            "createdAt": "2022-07-17T19:57:55+05:00",
            "modifiedAt": "2022-07-17T20:03:15+05:00",
            "extractedAt": "2022-10-19T04:06:19.915595800+00:00",
            "viewedAt": "",
            "collectionUuids": [],
            "metadata": {},
            "moreComments": {},
            "locationActualModifiedAt": "2022-10-19T04:06:19.915595800+00:00",
            "documentPages": 85,
            "uniqueId": ""
        },
        {
            "uuid": "703bd857-25f0-4033-a011-a6462d482a73",
            "title": "",
            "description": "Highlight",
            "light": "A complete decompilation of a program makes use of not only the decompiler but other\r\nrelated tools: the loader, the signature generator, the prototype generator, the disassembler,\r\nand the postprocessor. The loader loads the source binary program into memory, the signa\u0002ture generator generates signatures for known compilers and their libraries (if required), the\r\nprototype generator determines the formal argument types for library subroutines, the dis\u0002assembler parses the program and produces an assembler output \fle, the decompiler makes\r\nuse of the signature information to reduce the number of subroutines to decompile (i.e. it\r\ndoes not attempt to decompile library routines if they are recognized by a signature or the\r\nloader), and the postprocessor transforms the output decompiled high-level program into\r\na semantically equivalent program that makes use of speci\fc control structures available",
            "context": "Chapter 10\r\nConclusions\r\nThis thesis has presented techniques for the reverse compilation or decompilation of bi\u0002nary programs, and provided algorithms for the implementation of the di\u000berent phases\r\nof the decompiler. The methodology was implemented and tested in a prototype decom\u0002piler, dcc, which runs under DOS and Unix.\r\nDecompilers use similar principles and techniques used in compilers. A decompiler has\r\nseven di\u000berent phases, which incorporate compiler and optimization phases. There is no\r\nlexical analysis phase due to the simplicity of the source machine language. The syntax\r\nanalysis phase parses the source binary program separating code from data, and placing\r\ndata references in the symbol table. The main di\u000eculty with the separation of code from\r\ndata is that they are represented in the same way in von Neumann machines. The in\u0002termediate code generation phase generates a low-level intermediate representation of the\r\nprogram. The semantic analysis phase checks the semantic meaning of groups of low-level\r\ninstructions (idioms), gathers type information, and propagates it across the intermediate\r\nrepresentation. The control \row graph generation phase generates a control \row graph of\r\neach subroutine of the program, and attaches the intermediate representation information\r\nto the nodes of the graph. The data \row analysis phase analyzes the low-level intermediate\r\ncode and converts it into a high-level intermediate representation available in any high-level\r\nlanguage. The transformation of instructions eliminates all low-level references to condition\r\ncodes and registers, and introduces the high-level concept of expression. Subroutines that\r\nare not representable in a high-level language are \ragged. The structure of the program\r\nis analyzed in the control \row analysis phase, which structures the control \row graphs of\r\neach subroutine in the program. Finally, the code generation phase generates high-level\r\ncode based on the high-level intermediate representation and the structured graph of each\r\nsubroutine.\r\nA complete decompilation of a program makes use of not only the decompiler but other\r\nrelated tools: the loader, the signature generator, the prototype generator, the disassembler,\r\nand the postprocessor. The loader loads the source binary program into memory, the signa\u0002ture generator generates signatures for known compilers and their libraries (if required), the\r\nprototype generator determines the formal argument types for library subroutines, the dis\u0002assembler parses the program and produces an assembler output \fle, the decompiler makes\r\nuse of the signature information to reduce the number of subroutines to decompile (i.e. it\r\ndoes not attempt to decompile library routines if they are recognized by a signature or the\r\nloader), and the postprocessor transforms the output decompiled high-level program into\r\na semantically equivalent program that makes use of speci\fc control structures available",
            "fullText": "",
            "comment": "[[Summary]]",
            "commentAuthor": "Bo",
            "commentCreatedAt": "2021-09-21T09:09:46+05:00",
            "commentModifiedAt": "2021-09-21T09:10:25+05:00",
            "importance": 0,
            "locationActual": "302",
            "locationActualType": "pdf_page_index",
            "locationRaw": "302",
            "locationRawType": "pdf_page_index",
            "documentTitle": "[R] [[CifReverse94]] CifuentesC - 1994 - Reverse Compilation Techniques",
            "documentDescription": "",
            "documentReference": "",
            "documentPublicationYear": 0,
            "documentPublicationDatetime": "",
            "documentAuthor": "",
            "documentMetadata": {},
            "documentId": "",
            "documentIdType": "",
            "documentStorageId": "",
            "documentStorageIdType": "",
            "documentStorageUrl": "",
            "fileDirectory": "\\\\?\\D:\\Dropbox\\NEra\\New_Core_Reading",
            "fileFullName": "[R] [[CifReverse94]] CifuentesC - 1994 - Reverse Compilation Techniques.pdf",
            "fileExtension": "pdf",
            "fileFullPath": "",
            "selectTag": {
                "key": "summary",
                "rawTagString": "[[summary]]",
                "uuid": "c8ca3b19-1f81-4877-a044-6bdb89dd695c",
                "collectionUuids": [],
                "relatedTagUuids": []
            },
            "tags": [
                {
                    "key": "summary",
                    "rawTagString": "[[summary]]",
                    "uuid": "b03aa787-05d8-4efd-9e24-2c3cbe6d10b2",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 84,
                    "parentUuid": "703bd857-25f0-4033-a011-a6462d482a73"
                }
            ],
            "storageIdStr": "",
            "storageIdInt": 0,
            "storageDescription": "",
            "storageUrl": "",
            "createdAt": "2021-09-21T09:09:46+05:00",
            "modifiedAt": "2021-09-21T09:10:25+05:00",
            "extractedAt": "2022-10-18T22:33:15.676376900+00:00",
            "viewedAt": "",
            "collectionUuids": [],
            "metadata": {},
            "moreComments": {},
            "locationActualModifiedAt": "2022-10-18T22:33:15.676376900+00:00",
            "documentPages": 342,
            "uniqueId": ""
        },
        {
            "uuid": "74be596b-8be8-42b0-919c-51f9b38dc53d",
            "title": "",
            "description": "Underline",
            "light": "BEHAVIOR OF THE LOWER\r\nORGANISMS",
            "context": "T&'t&^^f\r\nCOLUMBIA UNIVERSITY BIOLOGICAL SERIES. X.\r\nBEHAVIOR OF THE LOWER\r\nORGANISMS\r\nBY H. S. JENNINGS\r\nASSISTANT PROFESSOR OF ZOOLOGY IN THE\r\nUNIVERSITY OF PENNSYLVANIA\r\nNcfo gork\r\nTHE COLUMBIA UNIVERSITY PRESS\r\nTHE MACMILLAN COMPANY, Agents LONDON: MACMILLAN & CO., Ltd. 1906\r\nAll rights reserved",
            "fullText": "",
            "comment": "Relatively important of study whose results were referenced by many in the begining of 20c. Jennings's book, from his post-doc work, sought to show even the lowest organisms, such as amoeba has internal structures that determines their behaviors. This book presents mostly data with some discussion of the implications. Jennings was also a pragmatist in his use of \"consciousness\". In this sense, behaviors that used to be thought of coming from higher faculties such as trial-and-error learning was already present in lower life forms already. He was following Spencer's linear progression of faculties. Both studying lower animals, Jennings and Loeb had opposite views buth both influenced Watson. Jennings was also a colleague of Watson at JHU.\r\n\r\n[[Summary]]",
            "commentAuthor": "Bo",
            "commentCreatedAt": "2022-07-11T16:47:23+05:00",
            "commentModifiedAt": "2022-07-11T16:50:57+05:00",
            "importance": 0,
            "locationActual": "6",
            "locationActualType": "pdf_page_index",
            "locationRaw": "6",
            "locationRawType": "pdf_page_index",
            "documentTitle": "[R] [[JenBehavior06]] JenningsH - 1906 - Behavior of the lower organisms",
            "documentDescription": "",
            "documentReference": "",
            "documentPublicationYear": 0,
            "documentPublicationDatetime": "",
            "documentAuthor": "",
            "documentMetadata": {},
            "documentId": "",
            "documentIdType": "",
            "documentStorageId": "",
            "documentStorageIdType": "",
            "documentStorageUrl": "",
            "fileDirectory": "\\\\?\\D:\\Dropbox\\NEra\\New_Core_Reading",
            "fileFullName": "[R] [[JenBehavior06]] JenningsH - 1906 - Behavior of the lower organisms.pdf",
            "fileExtension": "pdf",
            "fileFullPath": "",
            "selectTag": {
                "key": "summary",
                "rawTagString": "[[summary]]",
                "uuid": "ce797c79-7809-473e-b68f-7ada0463d97d",
                "collectionUuids": [],
                "relatedTagUuids": []
            },
            "tags": [
                {
                    "key": "summary",
                    "rawTagString": "[[summary]]",
                    "uuid": "e1de3c85-5529-4209-9090-9d2c6a218e4a",
                    "collectionUuids": [],
                    "relatedTagUuids": [],
                    "id": 170,
                    "parentUuid": "74be596b-8be8-42b0-919c-51f9b38dc53d"
                }
            ],
            "storageIdStr": "",
            "storageIdInt": 0,
            "storageDescription": "",
            "storageUrl": "",
            "createdAt": "2022-07-11T16:47:23+05:00",
            "modifiedAt": "2022-07-11T16:50:57+05:00",
            "extractedAt": "2022-10-19T03:01:28.636117+00:00",
            "viewedAt": "",
            "collectionUuids": [],
            "metadata": {},
            "moreComments": {},
            "locationActualModifiedAt": "2022-10-19T03:01:28.636117+00:00",
            "documentPages": 390,
            "uniqueId": ""
        }
    ],
    "responseMetadata": {
        "resultItems": 10,
        "offset": 0,
        "length": 10,
        "page": 0,
        "resultTotalPages": 2,
        "resultTotalItems": 20,
        "query": {
            "offset": 0,
            "length": 10,
            "page": 0,
            "filter": {
                "must": [
                    {
                        "field": "uuid",
                        "operator": 7,
                        "valueList": [
                            "f86be59b-41b6-46a9-b5a3-b76096fb2053",
                            "12d47c57-22ce-4478-aaea-b88abdb8546f",
                            "4331b195-9798-4b4a-81c6-09dc210f1449",
                            "f7df26f2-08aa-42d5-81d0-24cd05c52208",
                            "a3e5498f-9cd3-445b-b27f-f193cc643a23",
                            "da9d3500-061b-4e39-a905-ff3da84dc770",
                            "df631bfb-3cd7-4509-b384-32730180c26b",
                            "8d44b80b-4c7d-4f2a-beda-66e9e71f73ed",
                            "1e21ae38-5106-4375-9ec2-fb0f44ed466c",
                            "bd3b7c5f-dea2-49c2-bbde-187ad6e7ebe6",
                            "703bd857-25f0-4033-a011-a6462d482a73",
                            "9a665bc4-e093-4914-ab83-a206ab93d3af",
                            "23b40748-00d0-4a56-9b98-256de3e0849e",
                            "1cdb0505-fc6c-43fc-b094-281d434c2d85",
                            "5daa39d2-190b-4e7f-97f8-7de1f95ad408",
                            "68a57655-eeda-4e35-991c-9d91899da3e7",
                            "74be596b-8be8-42b0-919c-51f9b38dc53d",
                            "6de970b5-858f-45f5-9173-76fadae75208",
                            "ec780cef-b1d0-405b-b3c4-117651a828dc",
                            "b9157722-7031-4f50-89b8-d25d9af1b1f5"
                        ]
                    }
                ],
                "any": []
            },
            "findOne": false
        },
        "filterCount": 0,
        "filterReason": "whether the textual object is a firefly"
    }
}

