// @generated by protoc-gen-es v0.1.1 with parameter "target=ts"
// @generated from file common/importance/v1/importance.proto (package carrel.common.importance.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from enum carrel.common.importance.v1.Importance
 */
export enum Importance {
  /**
   * @generated from enum value: NO_IMPORTANCE = 0;
   */
  NO_IMPORTANCE = 0,

  /**
   * @generated from enum value: VERY_LOW = 1;
   */
  VERY_LOW = 1,

  /**
   * @generated from enum value: LOW = 2;
   */
  LOW = 2,

  /**
   * @generated from enum value: MEDIUM = 3;
   */
  MEDIUM = 3,

  /**
   * @generated from enum value: HIGH = 4;
   */
  HIGH = 4,

  /**
   * @generated from enum value: VERY_HIGH = 5;
   */
  VERY_HIGH = 5,

  /**
   * @generated from enum value: TOP_IMPORTANCE = 6;
   */
  TOP_IMPORTANCE = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(Importance)
proto3.util.setEnumType(Importance, "carrel.common.importance.v1.Importance", [
  { no: 0, name: "NO_IMPORTANCE" },
  { no: 1, name: "VERY_LOW" },
  { no: 2, name: "LOW" },
  { no: 3, name: "MEDIUM" },
  { no: 4, name: "HIGH" },
  { no: 5, name: "VERY_HIGH" },
  { no: 6, name: "TOP_IMPORTANCE" },
]);

