// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=ts"
// @generated from file carrel/server/fs_manager/v1/server_fs_manager_v1.proto (package carrel.server.fs_manager.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {GetDirectoryTreeRequest, GetDirectoryTreeResponse, ReadFileRequest, ReadFileResponse, WriteFileRequest, WriteFileResponse} from "./server_fs_manager_v1_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service carrel.server.fs_manager.v1.FSManagerService
 */
export const FSManagerService = {
  typeName: "carrel.server.fs_manager.v1.FSManagerService",
  methods: {
    /**
     * convert a directory to a directory tree structure
     *
     * @generated from rpc carrel.server.fs_manager.v1.FSManagerService.GetDirectoryTree
     */
    getDirectoryTree: {
      name: "GetDirectoryTree",
      I: GetDirectoryTreeRequest,
      O: GetDirectoryTreeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * read file content
     *
     * @generated from rpc carrel.server.fs_manager.v1.FSManagerService.ReadFile
     */
    readFile: {
      name: "ReadFile",
      I: ReadFileRequest,
      O: ReadFileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * write file content
     *
     * @generated from rpc carrel.server.fs_manager.v1.FSManagerService.WriteFile
     */
    writeFile: {
      name: "WriteFile",
      I: WriteFileRequest,
      O: WriteFileResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

