// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=ts"
// @generated from file carrel/server/firefly_keeper/v1/firefly_keeper.proto (package carrel.server.firefly_keeper.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {DirectoryRequest} from "../../../generic/api/request_directory/v1/request_directory_pb.js";
import {FireFliesResponse} from "./firefly_keeper_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service carrel.server.firefly_keeper.v1.FirefliesService
 */
export const FirefliesService = {
  typeName: "carrel.server.firefly_keeper.v1.FirefliesService",
  methods: {
    /**
     * @generated from rpc carrel.server.firefly_keeper.v1.FirefliesService.ScanFolderForFireflies
     */
    scanFolderForFireflies: {
      name: "ScanFolderForFireflies",
      I: DirectoryRequest,
      O: FireFliesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

