// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=ts"
// @generated from file carrel/server/scaffold/v1/server_scaffold_v1.proto (package carrel.server.scaffold.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {ScaffoldNewProjectRequest, ScaffoldNewProjectResponse} from "./server_scaffold_v1_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service carrel.server.scaffold.v1.ScaffoldNewProjectService
 */
export const ScaffoldNewProjectService = {
  typeName: "carrel.server.scaffold.v1.ScaffoldNewProjectService",
  methods: {
    /**
     * @generated from rpc carrel.server.scaffold.v1.ScaffoldNewProjectService.ScaffoldNewProject
     */
    scaffoldNewProject: {
      name: "ScaffoldNewProject",
      I: ScaffoldNewProjectRequest,
      O: ScaffoldNewProjectResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

