// @generated by protoc-gen-es v0.1.1 with parameter "target=ts"
// @generated from file carrel/core/shared/v1/core_shared_v1.proto (package carrel.core.shared.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * core components of carrel
 *
 * @generated from enum carrel.core.shared.v1.CarrelComponent
 */
export enum CarrelComponent {
  /**
   * @generated from enum value: CARREL_COMPONENT_CARREL_UNSPECIFIED = 0;
   */
  CARREL_UNSPECIFIED = 0,

  /**
   * Project-wide tag management
   *
   * @generated from enum value: CARREL_COMPONENT_FIREFLY_KEEPER = 1;
   */
  FIREFLY_KEEPER = 1,

  /**
   * Exploratory research that gives you insight into humanities data. working mostly with Stacks
   *
   * @generated from enum value: CARREL_COMPONENT_CANDOR = 2;
   */
  CANDOR = 2,

  /**
   * Notes management and writing companion using TO.
   *
   * @generated from enum value: CARREL_COMPONENT_CABINET = 3;
   */
  CABINET = 3,

  /**
   * A general-purpose DB for storing relational humanities data.
   *
   * @generated from enum value: CARREL_COMPONENT_INTERACT = 4;
   */
  INTERACT = 4,

  /**
   * Writing progress tracking and organizer. Also Organizer and planner of points
   *
   * @generated from enum value: CARREL_COMPONENT_WRITING_PLAN = 5;
   */
  WRITING_PLAN = 5,

  /**
   * Manager of research materials.
   *
   * @generated from enum value: CARREL_COMPONENT_STACKS = 6;
   */
  STACKS = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(CarrelComponent)
proto3.util.setEnumType(CarrelComponent, "carrel.core.shared.v1.CarrelComponent", [
  { no: 0, name: "CARREL_COMPONENT_CARREL_UNSPECIFIED" },
  { no: 1, name: "CARREL_COMPONENT_FIREFLY_KEEPER" },
  { no: 2, name: "CARREL_COMPONENT_CANDOR" },
  { no: 3, name: "CARREL_COMPONENT_CABINET" },
  { no: 4, name: "CARREL_COMPONENT_INTERACT" },
  { no: 5, name: "CARREL_COMPONENT_WRITING_PLAN" },
  { no: 6, name: "CARREL_COMPONENT_STACKS" },
]);

