[package]
name = "pdf_gongju"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
carrel_commons = { path = "../carrel_commons" }
carrel_utils = { path = "../carrel/carrel_utils" }
uuid = { version = "1.1.2", features = ["serde", "v4"] }
pdfium-render = "0.7.21"
regex = "1.6.0"
serde_json = "1.0.85"
thiserror = "1.0.37"
chrono= { version = "0.4.19", features = ["serde"] }
log = "0.4.14"
simplelog = "0.12.0"
to_core = { path = "../to/to_core"}

[dev-dependencies]
carrel_utils = { path = "../carrel/carrel_utils" }
