

export enum ViewId {
    EMPTY = 'EMPTY',
    CORE_TAG_TREE = 'CORE_TAG_TREE',
    CARREL_WRITER = 'CARREL_WRITER',
    ARCHIVE_LIST = 'ARCHIVE_LIST',
    CARD_BLOCK = 'CARD_BLOCK',
    INSPECTOR_BLOCK = 'INSPECTOR_BLOCK',
    CORE_TAG_FIREFLIES = 'CORE_TAG_FIREFLIES',
    ARCHIVE_FILES = 'ARCHIVE_FILES',
}
