[package]
name = "carrel_app_db_migration"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
carrel_utils = { path = "../../carrel_utils" }
tokio = { version = "1.0", features = ["full"] }


[dependencies.sea-orm-migration]
version = "^0.9.3"
features = [
    "runtime-tokio-rustls",  # `ASYNC_RUNTIME` feature
    "sqlx-sqlite",         # `DATABASE_DRIVER` feature
]
